proyecto001/urls.py
from django.contrib import admin
from django.urls import path
from miapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name = "inicio"),
    path('listado_paises/', views.cursos, name='cursos'),
    path('registrar_paises/', views.crear_curso, name='crear_curso'),
    path('eliminar_paises/<int:curso_id>/', views.eliminar_curso, name='eliminar_curso'),
    path('listado_editorial/', views.listar_carreras, name='carreras'),
    path('registrar_editorial/', views.crear_carrera, name='crear_carrera'),
    path('eliminar_editorial/<int:carrera_id>/', views.eliminar_carrera, name='eliminar_carrera'),
    path('editar_editorial/<int:carrera_id>/', views.editar_carrera, name='editar_carrera'),
    path('integrantes/',views.integrantes, name = "integrantes"),

]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miapp/models.py
# mi_aplicacion/models.py

from django.db import models

class Course(models.Model):
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=40)
    hour = models.IntegerField()
    credits = models.IntegerField()
    state = models.BooleanField()


class Career(models.Model):
    name = models.CharField(max_length=100)
    shortname = models.CharField(max_length=50)
    image = models.ImageField(upload_to='careers/', null=True, blank=True)
    state = models.BooleanField()

    def __str__(self):
        return self.name

miapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, HttpResponse, redirect
from miapp.models import Course
from miapp.models import Career
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages


def index(request):
   
    return render(request,'index.html', {
})

def carreras(request):
    return render(request,'carreras.html',{
})

def crear_curso(request):
    return render(request,'crear_curso.html',{
})
def crear_carrera(request):
    return render(request,'crear_carrera.html',{
})

def inicio(request):
    return render(request,'layout.html',{
    })

def cursos(request):
    cursos = Course.objects.all()
    return render(request, 'cursos.html', {'cursos': cursos})

def crear_curso(request):
    if request.method == 'POST':
        code = request.POST.get('code')
        name = request.POST.get('name')
        hour = 0
        credits = request.POST.get('credits')
        state = request.POST.get('state')

        # Validación de campos (puedes agregar más validaciones según tus necesidades)
        if not code or not name or not credits:
            messages.error(request, 'Todos los campos son obligatorios')
        else:
            course = Course(code=code, name=name, hour=0, credits=credits, state=state)
            course.save()
            messages.success(request, 'Pais agregado correctamente')

    return render(request, 'crear_curso.html')



def eliminar_curso(request, curso_id):
    course = get_object_or_404(Course, id=curso_id)
    course.delete()
    return redirect('cursos')

def listar_carreras(request):
    carreras = Career.objects.all()
    return render(request, 'carreras.html', {'carreras': carreras})

def crear_carrera(request):
    if request.method == 'POST':
        name = request.POST['name']
        shortname = request.POST['shortname']
        image = request.FILES.get('image')  # Usa request.FILES para obtener la imagen enviada

        # Obtenemos el valor del campo state como un string ('on' o None)
        state_str = request.POST.get('state', None)

        # Convertimos el string a un valor booleano válido (True o False)
        state = True if state_str == 'on' else False

        Career.objects.create(name=name, shortname=shortname, image=image, state=state)
        messages.success(request, 'Editorial agregada exitosamente.')
        return redirect('carreras')

    return render(request, 'crear_carrera.html')

def eliminar_carrera(request, carrera_id):
    carrera = get_object_or_404(Career, id=carrera_id)
    carrera.delete()
    messages.success(request, 'Editorial eliminada exitosamente.')
    return redirect('carreras')

def editar_carrera(request, carrera_id):
    carrera = get_object_or_404(Career, id=carrera_id)

    if request.method == 'POST':
        name = request.POST['name']
        shortname = request.POST['shortname']
        image = request.FILES.get('image', carrera.image)
        state = True if request.POST.get('state', False) else False

        carrera.name = name
        carrera.shortname = shortname
        carrera.image = image
        carrera.state = state
        carrera.save()

        messages.success(request, 'Editorial actualizada exitosamente.')
        return redirect('carreras')

    return render(request, 'editar_carrera.html', {'carrera': carrera})

def integrantes(request):
    return render(request,'integrantes.html',{
})

miapp/templates/carreras.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Listado de Editoriales</h1>
    <table>
        <tr>
            <th>Nombre</th>
            <th>URL</th>
            <th>Imagen</th>
            <th>Estado</th>
            <th>Acciones</th>
        </tr>
        {% for carrera in carreras %}
        <tr>
            <td>{{ carrera.name }}</td>
            <td>{{ carrera.shortname }}</td>
            <td>
                {% if carrera.image %}
                    <img src="{{ carrera.image.url }}"width="50">
                {% else %}
                    <span class="no-image">Sin imagen</span>
                {% endif %}
            </td>
            <td>{{ carrera.state }}</td>
            <td class="actions">
                <a href="{% url 'editar_carrera' carrera.id %}">Editar</a>
                <a href="{% url 'eliminar_carrera' carrera.id %}">Eliminar</a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

miapp/templates/crear_carrera.html
{% extends 'layout.html' %}
{% block content %}
    <h1>Registrar Editorial</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="name">Nombre:</label>
        <input type="text" id="name" name="name" required><br>
        <label for="shortname">URL: </label>
        <input type="text" id="shortname" name="shortname" required><br>
        <label for="image">Imagen:</label>
        <input type="file" id="image" name="image"><br>
        <label for="state">Estado:</label>
        <select name="state">
            <option value="1"> Si </option>
            <option value="0"> No </option>
        </select>
        <input type="submit" value="Registrar">
    </form>
{% endblock %}

miapp/templates/crear_curso.html
{% extends 'layout.html' %}

{% block content %}
<h1>Registrar Pais</h1>
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <label for="code">IDPais:</label>
        <input type="text" name="code" id="code">
        <label for="name">Nombre:</label>
        <input type="text" name="name" id="name">
        <label for="credits">Poblacion:</label>
        <input type="number" name="credits" id="credits">
        <label for="state">State:</label>
        <select name="state">
            <option value="1"> Si </option>
            <option value="0"> No </option>
        </select>
        <input type="submit" value="Agregar Pais">
    </form>
{% endblock %}

miapp/templates/crear_editorial.html
{% extends 'layout.html' %}
{% block title %}
{{titulo}}
{% endblock %}
{% block content %}
<h1 class="title">Agregar Nueva Editorial</h1>
{% endblock %}

miapp/templates/cursos.html
{% extends 'layout.html' %}
{% block content %}
<h1>Listado de Paises</h1>
<!DOCTYPE html>
<html>
<head>
    <title>Listado de Paises</title>
</head>
<body>
    <div class="listacurso">
        <ul>
        {% for curso in cursos %}
        <li>
            {{ curso.name }} (IDPais: {{ curso.code }}) - Poblacion: {{ curso.credits }}- State: {{ curso.state }}
            <a href="{% url 'eliminar_curso' curso.id %}">Eliminar</a>
        </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>
{% endblock %}

miapp/templates/editar_carrera.html
<!-- editar_carrera.html -->
{% extends 'layout.html' %}


{% block title %}Editar Carrera{% endblock %}

{% block content %}
<div style="display: flex; justify-content: center; align-items: center; height: 30vh;">
    <div style="width: 20%;">
    <h1>Editar Carrera</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_name" style="display: block; margin-bottom: 5px;">Nombre:</label>
        <input type="text" name="name" id="id_name" value="{{ carrera.name }}" style="width: 100%; padding: 5px; margin-bottom: 10px;">
        
        <label for="id_shortname" style="display: block; margin-bottom: 5px;">Nombre corto:</label>
        <input type="text" name="shortname" id="id_shortname" value="{{ carrera.shortname }}" style="width: 100%; padding: 5px; margin-bottom: 10px;">
        
        <label for="id_image" style="display: block; margin-bottom: 5px;">Imagen:</label>
        <input type="file" name="image" id="id_image" style="width: 100%; padding: 5px; margin-bottom: 10px;">
        
        <label for="id_state" style="display: block; margin-bottom: 5px;">Estado:</label>
        <input type="checkbox" name="state" id="id_state" {% if carrera.state %}checked{% endif %} style="margin-right: 5px;"><br>
        
        <input type="submit" value="Guardar" style="background-color: #4CAF50; color: #fff; padding: 10px 15px; border: none; cursor: pointer;">
    </form>
</div>
</div>
{% endblock %}

miapp/templates/editorial.html
{% extends 'layout.html' %}

{% block content %}
<h1 class="title">Listado de Editoriales</h1>

{% endblock %}

miapp/templates/index.html
{% extends 'layout.html' %}
{% block title %}
    {{titulo}}
{% endblock %}

{% block content %}

    <h1 class="title">Listado de Países</h1>

{% endblock %}

miapp/templates/integrantes.html
{% extends 'layout.html' %}

{% block content %}
<h1 class="title">Integrantes</h1>
    <h2>- Guillén Ayala, Bryam</h2>
    <h2>- Montes Palacios, Luis Enrrique</h2>
    <h2>- Timana Espinoza, Marcia Kori</h2>

{% endblock %}

miapp/templates/layout.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/esti.css' %}" />
</head>

<body>
    <header>
        <div id="logotipo">
            <img src="{% static 'images/loguito.png' %}" width="400" height="80" />
        </div>
    </header>
    <nav>
        <ul >
            <li >
                <a  href="{% url 'cursos' %}"><h2>Listado Paises</h2></a>
            </li>
            <li>
                <a href="{% url 'crear_curso' %}"><h2>Registrar Pais</h2></a>
            </li>
            <li>
                <a href="{% url 'carreras' %}"><h2>Editorial</h2></a>
            </li>
            <li>
                <a href="{% url 'crear_carrera' %}"><h2>Crear Editorial</h2></a>
            </li>
            <li>
                <a href="{% url 'integrantes' %}"><h2>Integrantes</h2></a>
            </li>
        </ul>
    </nav>
    <div class="barra">
        <span class="esquina-izquierda"></span>
        <span class="relleno-barra"></span>
        <span class="esquina-derecha"></span>
    </div>
    <div id="content">
        <div class="box">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <footer>
        UNTELS - Lenguaje de Programación III &copy; Guillen Ayala - Timana Espinoza - Montes Palacios {% now "d/m/Y h:m:s" %}
    </footer>
</body>
</html>

miapp/templates/registrar_pais.html
{% extends 'layout.html' %}
{% block title %}
{{titulo}}
{% endblock %}
{% block content %}
<h1 class="title">Registrar Nuevo País</h1>
{% endblock %}